// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculationAPI.Data;

#nullable disable

namespace TaxCalculationAPI.Migrations
{
    [DbContext(typeof(TaxCalculationDBContext))]
    [Migration("20240127102632_UpdateTableStructure")]
    partial class UpdateTableStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculation.Data.CalculatedTax", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AnnualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedTaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CalculatedTax", (string)null);
                });

            modelBuilder.Entity("TaxCalculation.Data.CalculationType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("RateFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RatePercentage")
                        .HasColumnType("int");

                    b.Property<decimal>("RateTo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxCalculationTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("CalculationType", (string)null);
                });

            modelBuilder.Entity("TaxCalculation.Data.PostalCode", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TaxCalculationTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("PostalCodes", (string)null);
                });

            modelBuilder.Entity("TaxCalculation.Data.TaxType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TaxType", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
